const Discord = require("discord.js")
module.exports.run = async(bot, message, prefix) =>{
  let msg = message.content.toLowerCase()
  let Owner = message.guild.roles.find(r => r.name == "Owner")    
  let Staff = message.guild.roles.find(r => r.name == "Staff")
  let PlayerRole = message.guild.roles.find(r => r.name == "Player")
  let muted = message.guild.roles.find(r => r.name == "Muted")
  let pingRole = message.guild.roles.find(r => r.name == "Ping")
  let args = msg.split(" ").slice(1)
  let rUser = message.guild.member(message.mentions.users.first() || message.guild.members.get(args[0]))
  let rreason = args.slice(1).join(" ")
  message.delete()
  if (!message.member.roles.has(Owner.id) && !message.member.roles.has(Staff.id)) return message.channel.send("You do not have access to this command")
  if (!rUser) return message.channel.send('This user doesn\'t exist')
  let denyEmbed = new Discord.RichEmbed()
  .setDescription("**___User Denied___**")
  .setColor(0xFF0000)
  .addField('Name of user denied:', rUser)
  .addField('Reason', rreason)
  .addField('Retry', "Dont worry, you can just apply again!")
  message.guild.channels.find(c => c.name == "newcomers-and-applications").send(denyEmbed)  
}
